server:
  port: 8888


# camunda登录信息配置
camunda.bpm:
  admin-user:
    id: admin  #用户名
    password: 123456  #密码
    firstName: yu
  filter:
    create: All tasks
  auto-deployment-enabled: true

# mysql连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?nullDatabaseMeansCurrent=true
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlDataSource

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  # mvc策略
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    com:
      sy: debug
    org:
      camunda: debug
